### PR TITLE
Better x64 codegen

### PR DESCRIPTION
**Pull request by zhiayang**
Please don't feel pressured to merge this! I just went into rabbit hole and basically rewrote the entire codegen ><

### CODE REVIEW

**Comment by rexim** [comment]
@zhiayang oh, this looks cool! I like that's shorter now! I'll look into it deeper a bit later... Thank you so much!

**Comment by zhiayang** [comment]
just for fun, calculating pi 100 times (i just modified `pi.basm` so it would be called 100 times):

before:
```
real: 2.56 s, usr: 2.52 s, sys: 0.02 s
```

after:
```
real: 711.20 ms, usr: 696.68 ms, sys: 10.52 ms
```

**Review by rexim — CHANGES_REQUESTED** [review]
1. I think we should not depend on the NASM features too much because the whole point of this operation is to eventually get rid of NASM and replace it with our own native code generation. If we depend too much on NASM we won't be able to easily do that. We just need to figure out what instructions we need.

2. We don't need to use macro language of NASM. We already are using a macro language on top of the NASM. It's called C. We are generating NASM code with C. All of those macros (`STCK_PUSH`, `STACK_POP`, etc), could be C functions that spit out the corresponding NASM code. And in the future, when we replace NASM with native code, those function will simply output the native code intead of NASM.

I'm okay with merging this, only if we get rid of NASM macros and replace them with the C functions.

**Comment by zhiayang** [comment]
been a bit busy lately, but done

**Comment by rexim** [comment]
@zhiayang looks goode to me! :+1: Thank you for your contribution! :kissing:

**Pull request merged**
