### PR TITLE
(#295) Add SDL binary dependency to the repo

### LINKED ISSUE #295: consider adding the SDL binary dependency to the repo
introduced in #294

It is actually quite common for Windows C/C++ project to have binary blobs in the repos. So there is nothing to be ashamed about.

### PR DESCRIPTION
**Pull request by kolumb**
Close #295 
Just added files from https://www.libsdl.org/release/SDL2-devel-2.0.12-VC.zip from `include` and `lib` folders
Lib files are 64 bit versions. Didn't included `SDL2test.lib` and `SDL2.dll`.
But now on Windows sdl example works if I execute this commands:
```cmd
cl.exe nobuild.c
nobuild examples
build\toolchain\bme build\examples\sdl.bm -n build\wrappers\libbm_sdl.dll
```

### CODE REVIEW

**Comment by Ciremun** [comment]
it still expects x64 `SDL2.dll` in path or same dir, otherwise fails with `ERROR: could not load object build\wrappers\libbm_sdl.dll: 126 (ERROR_MOD_NOT_FOUND)`

**Comment by kolumb** [comment]
Interesting... I don't have SDL2.dll in folder neither in path.

**Comment by Ciremun** [comment]
@kolumb you could use this code to get the loaded dll path:
```c
#include <stdio.h>
#include <windows.h>

int main(void)
{
    HMODULE hModule = LoadLibraryA("SDL2.dll");
    LPSTR path[_MAX_PATH];
    GetModuleFileNameA(hModule, path, _MAX_PATH);
    printf("path: %s\n", (char *)path);
    return 0;
}
```

**Comment by kolumb** [comment]
Oh, you right, it found it. I'm pepega :D

**Pull request closed without merging**
